# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string
tp @s ^-0.21875 ^1.25 ^0 ~0 ~0
data merge entity @s {width:0.25f,height:0.25f,response:1b}
tag @s add menu.hitbox.handle
tag @s add menu.hitbox