# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.bestiary.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bestiary', 'function_path': 'animated_java:bestiary/animations/despawn/play'}
tag @s add aj.bestiary.animation.despawn.playing
scoreboard players set @s aj.despawn.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:bestiary/animations/despawn/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only