# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.locator
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator6
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator2
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator5
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator3
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator4
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator7
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator8
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator9
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.locator10
function animated_java:main_ui/zzz/at_all_locators/execute_at_transform with storage aj:temp args