# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fishing_rod.root] run return 0
execute on passengers if entity @s[tag=aj.fishing_rod.data] unless data entity @s {data:{rigHash: 'a46d0cc83f069f551a7923a22dec115a89cacf8334bddbd47c99f07256fd20d7'}} on vehicle run function animated_java:fishing_rod/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1