# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fishing_rod.root] run return 0
execute on passengers if entity @s[tag=aj.fishing_rod.data] unless data entity @s {data:{rigHash: '9d1deee312137751d742f6ec35fdc01c86f3e23f3390e044819b1c9cf0471a19'}} on vehicle run function animated_java:fishing_rod/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1