# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fishing_rod.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.fishing_rod.animation.idle.playing] run function animated_java:fishing_rod/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.fishing_rod.animation.charging.playing] run function animated_java:fishing_rod/animations/charging/zzz/on_tick
execute if entity @s[tag=aj.fishing_rod.animation.casting.playing] run function animated_java:fishing_rod/animations/casting/zzz/on_tick
execute if entity @s[tag=aj.fishing_rod.animation.cast_idle.playing] run function animated_java:fishing_rod/animations/cast_idle/zzz/on_tick
execute if entity @s[tag=aj.fishing_rod.animation.retrieve.playing] run function animated_java:fishing_rod/animations/retrieve/zzz/on_tick
execute on passengers if entity @s[tag=aj.fishing_rod.data] run function animated_java:fishing_rod/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~