# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:interaction ^-0.21875 ^1.25 ^0 {Tags:["aj.global.bone.handle.child","aj.global.bone.handle.child.locator","aj.global.bone.handle.decendant","aj.global.bone.handle.decendant.locator","aj.global.bone.handle.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.main_ui.bone.handle.child","aj.main_ui.bone.handle.child.locator","aj.main_ui.bone.handle.decendant","aj.main_ui.bone.handle.decendant.locator","aj.main_ui.bone.handle.tree","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator","aj.main_ui.node","aj.main_ui.node.locator","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator, distance=..2.546163700103856 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator
data modify entity @s data.uuids.locator_locator set from storage aj:uuid main.out
data modify entity @s data.locators.locator.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^0.84375 ^1.25 ^0 {Tags:["aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.bone.string.child","aj.global.bone.string.child.locator","aj.global.bone.string.decendant","aj.global.bone.string.decendant.locator","aj.global.bone.string.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator6","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.bone.string.child","aj.main_ui.bone.string.child.locator","aj.main_ui.bone.string.decendant","aj.main_ui.bone.string.decendant.locator","aj.main_ui.bone.string.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator6","aj.main_ui.node","aj.main_ui.node.locator6","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator6, distance=..2.7210212266267955 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator6
data modify entity @s data.uuids.locator_locator6 set from storage aj:uuid main.out
data modify entity @s data.locators.locator6.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^-0.21875 ^0.75 ^0 {Tags:["aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator2","aj.main_ui.bone.body.child","aj.main_ui.bone.body.child.locator","aj.main_ui.bone.body.decendant","aj.main_ui.bone.body.decendant.locator","aj.main_ui.bone.body.tree","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator2","aj.main_ui.node","aj.main_ui.node.locator2","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator2, distance=..2.596199098640267 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator2
data modify entity @s data.uuids.locator_locator2 set from storage aj:uuid main.out
data modify entity @s data.locators.locator2.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^0.84375 ^0.75 ^0 {Tags:["aj.global.bone.bobber.child","aj.global.bone.bobber.child.locator","aj.global.bone.bobber.decendant","aj.global.bone.bobber.decendant.locator","aj.global.bone.bobber.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator5","aj.main_ui.bone.bobber.child","aj.main_ui.bone.bobber.child.locator","aj.main_ui.bone.bobber.decendant","aj.main_ui.bone.bobber.decendant.locator","aj.main_ui.bone.bobber.tree","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator5","aj.main_ui.node","aj.main_ui.node.locator5","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator5, distance=..2.7921813698674587 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator5
data modify entity @s data.uuids.locator_locator5 set from storage aj:uuid main.out
data modify entity @s data.locators.locator5.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^-0.21875 ^0.25 ^0 {Tags:["aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.reel.child","aj.global.bone.reel.child.locator","aj.global.bone.reel.decendant","aj.global.bone.reel.decendant.locator","aj.global.bone.reel.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator3","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.reel.child","aj.main_ui.bone.reel.child.locator","aj.main_ui.bone.reel.decendant","aj.main_ui.bone.reel.decendant.locator","aj.main_ui.bone.reel.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator3","aj.main_ui.node","aj.main_ui.node.locator3","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator3, distance=..2.815998778220955 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator3
data modify entity @s data.uuids.locator_locator3 set from storage aj:uuid main.out
data modify entity @s data.locators.locator3.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^0.84375 ^0.25 ^0 {Tags:["aj.global.bone.hook.child","aj.global.bone.hook.child.locator","aj.global.bone.hook.decendant","aj.global.bone.hook.decendant.locator","aj.global.bone.hook.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.locator","aj.global.bone.main.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator4","aj.main_ui.bone.hook.child","aj.main_ui.bone.hook.child.locator","aj.main_ui.bone.hook.decendant","aj.main_ui.bone.hook.decendant.locator","aj.main_ui.bone.hook.tree","aj.main_ui.bone.main.decendant","aj.main_ui.bone.main.decendant.locator","aj.main_ui.bone.main.tree","aj.main_ui.bone.root.decendant","aj.main_ui.bone.root.decendant.locator","aj.main_ui.bone.root.tree","aj.main_ui.entity","aj.main_ui.locator","aj.main_ui.locator.locator4","aj.main_ui.node","aj.main_ui.node.locator4","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.main_ui.locator.locator4, distance=..2.9904557424117724 ] run function animated_java:main_ui/zzz/summon/as_data_entity/as_locator/locator4
data modify entity @s data.uuids.locator_locator4 set from storage aj:uuid main.out
data modify entity @s data.locators.locator4.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.handle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_handle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.string] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_string set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.bobber] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bobber set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.reel] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_reel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.item_display11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.hook] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hook set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.main] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_main set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.corner1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_corner1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.corner2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_corner2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.corner4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_corner4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.main_ui.node.corner3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_corner3 set from storage aj:uuid main.out