# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator6
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator2
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator5
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator3
function animated_java:main_ui/remove/zzz/this/kill_locator with entity @s data.locators.locator_locator4