# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,-1.8062f,0f,0f,-1f,-0.8405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,-1.6812f,0f,0f,-1f,-0.8405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,1.25f,0f,0.1938f,0f,0f,-1.25f,-0.8405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.766f,-0.6428f,-1.1904f,0f,-0.6428f,-0.766f,0.4025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.0533f,-0.8838f,-1.3962f,0f,-0.8838f,-1.0533f,0.4733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.766f,-0.6428f,-1.875f,0f,-0.6428f,-0.766f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.49999999999999994,"posy":0.18374444088225372,"posz":-0.8524917010325747,"roty":0,"rotx":-40.00000000000001}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fishing_rod/animations/charging/zzz/frames/60_root_commands