# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.2052f,0f,0f,0f,3.2102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.2052f,0f,0f,0f,3.2102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.2052f,0f,0f,0f,3.2103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.5f,0.866f,2.2214f,0f,0.866f,-0.5f,1.6312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,0.6875f,1.1908f,2.1875f,0f,1.1908f,-0.6875f,1.4163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.5f,0.866f,1.875f,0f,0.866f,-0.5f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000004,"posy":3.21875,"posz":3.2024432726706786,"roty":0,"rotx":60}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fishing_rod/animations/casting/zzz/frames/2_root_commands