# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.1698f,0f,0f,0f,3.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.1698f,0f,0f,0f,3.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.1698f,0f,0f,0f,3.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.5f,0.866f,-1.1536f,0f,0.866f,-0.5f,1.4437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,0.6875f,1.1908f,-1.1875f,0f,1.1908f,-0.6875f,1.2288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.5f,0.866f,-1.5f,0f,0.866f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000004,"posy":-0.15624999999999978,"posz":3.0149432726706786,"roty":0,"rotx":60}}}