# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.2155f,0f,0f,0f,2.7563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.2155f,0f,0f,0f,2.7563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.2155f,0f,0f,0f,2.7563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.6428f,0.766f,-1.0275f,0f,0.766f,-0.6428f,1.3721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,0.8838f,1.0533f,-1.0983f,0f,1.0533f,-0.8838f,1.1663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.6428f,0.766f,-1.5f,0f,0.766f,-0.6428f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000004,"posy":0.22749170103257432,"posz":2.7462444408822533,"roty":0,"rotx":50.00000000000002}}}