# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.1229f,0f,0f,0f,3.2552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.1229f,0f,0f,0f,3.2552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,3.1229f,0f,0f,0f,3.2553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.4695f,0.8829f,2.1948f,0f,0.8829f,-0.4695f,1.6429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,0.6455f,1.2141f,2.1684f,0f,1.2141f,-0.6455f,1.4268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.4695f,0.8829f,1.875f,0f,0.8829f,-0.4695f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000004,"posy":3.136704824987082,"posz":3.2479216558083657,"roty":0,"rotx":62}}}