# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.2729f,0f,0f,0f,3.266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.2729f,0f,0f,0f,3.266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.2729f,0f,0f,0f,3.2661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.4617f,0.887f,-1.1869f,0f,0.887f,-0.4617f,1.6456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,0.6349f,1.2196f,-1.2114f,0f,1.2196f,-0.6349f,1.4294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.4617f,0.887f,-1.5f,0f,0.887f,-0.4617f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000004,"posy":-0.2590506019308463,"posz":3.258841614166471,"roty":0,"rotx":62.50000000000001}}}