# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fishing_rod/animations/cast_idle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.cast_idle.frame 1