# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.7864f,0f,0f,0f,2.1001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.7864f,0f,0f,0f,2.1001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.7864f,0f,0f,0f,2.1001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.8538f,0.5206f,-0.8336f,0f,0.5206f,-0.8538f,1.1854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.1739f,0.7159f,-0.9664f,0f,0.7159f,-1.1739f,1.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.8538f,0.5206f,-1.5f,0f,0.5206f,-0.8538f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5000000000000002,"posy":0.7945285076384928,"posz":2.086712341867478,"roty":0,"rotx":31.375000000000004}}}