# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.charging.frame dummy
scoreboard objectives add aj.casting.frame dummy
scoreboard objectives add aj.cast_idle.frame dummy
scoreboard objectives add aj.retrieve.frame dummy