# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bestiary.root] run return 0
execute on passengers if entity @s[tag=aj.bestiary.data] unless data entity @s {data:{rigHash: 'f35d577d0c0e7f4d0a74f926b6d001481691a50f4ba00cc14342311cf4e75ea2'}} on vehicle run function animated_java:bestiary/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1