# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bestiary.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.bestiary.animation.spawn.playing] run function animated_java:bestiary/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.bestiary.animation.despawn.playing] run function animated_java:bestiary/animations/despawn/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~