# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_model3) {transformation: [-0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.6139f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishname3) {transformation: [0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.6348f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishcount3) {transformation: [0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.5827f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_model5) {transformation: [-0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.6139f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishname5) {transformation: [0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.6348f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishcount5) {transformation: [0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.5827f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_model8) {transformation: [-0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.541f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishname8) {transformation: [0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.5618f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishcount8) {transformation: [0.0417f,0f,0f,-0.0312f,0f,0.0417f,0f,0.5098f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_model7) {transformation: [-0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.541f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishname7) {transformation: [0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.5618f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_fishcount7) {transformation: [0.0417f,0f,0f,0.0313f,0f,0.0417f,0f,0.5098f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_text_display2) {transformation: [0.0833f,0f,0f,0f,0f,0.0833f,0f,0.6608f,0f,0f,1f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rare) {transformation: [-0.1667f,0f,0f,0f,0f,0.1667f,0f,0.5742f,0f,0f,-1f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}