# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator6
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator2
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator5
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator3
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_locator4
function animated_java:main_ui/zzz/as_all_locators/execute_as_uuid with storage aj:temp args