# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.main_ui.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'main_ui', 'function_path': 'animated_java:main_ui/animations/despawn/next_frame'}
execute if score @s aj.despawn.frame matches 36.. run scoreboard players set @s aj.despawn.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.despawn.frame
execute at @s run function animated_java:main_ui/animations/despawn/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.despawn.frame 1