# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:marker ^0 ^2.6875 ^0 {Tags:["aj.fishing_rod.bone.body.child","aj.fishing_rod.bone.body.child.locator","aj.fishing_rod.bone.body.decendant","aj.fishing_rod.bone.body.decendant.locator","aj.fishing_rod.bone.body.tree","aj.fishing_rod.bone.handle.decendant","aj.fishing_rod.bone.handle.decendant.locator","aj.fishing_rod.bone.handle.tree","aj.fishing_rod.bone.root.decendant","aj.fishing_rod.bone.root.decendant.locator","aj.fishing_rod.bone.root.tree","aj.fishing_rod.entity","aj.fishing_rod.locator","aj.fishing_rod.locator.locator","aj.fishing_rod.node","aj.fishing_rod.node.locator","aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.bone.handle.decendant","aj.global.bone.handle.decendant.locator","aj.global.bone.handle.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.new, tag=aj.fishing_rod.locator.locator, distance=..4.72895385321254 ] run function animated_java:fishing_rod/zzz/summon/as_data_entity/as_locator/locator
data modify entity @s data.uuids.locator_locator set from storage aj:uuid main.out
data modify entity @s data.locators.locator.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.hook] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hook set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.bobber] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bobber set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.string] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_string set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.reel] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_reel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fishing_rod.node.handle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_handle set from storage aj:uuid main.out