# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.fishing_rod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fishing_rod', 'function_path': 'animated_java:fishing_rod/animations/pause_all'}
tag @s remove aj.fishing_rod.animation.idle.playing
tag @s remove aj.fishing_rod.animation.charging.playing
tag @s remove aj.fishing_rod.animation.casting.playing
tag @s remove aj.fishing_rod.animation.cast_idle.playing
tag @s remove aj.fishing_rod.animation.retrieve.playing