# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display7) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display9) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display5) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display11) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner1) {transformation: [0.038f,-0.0325f,0f,0f,0.0325f,0.038f,0f,-0.9656f,0f,0f,0.05f,0.7875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner2) {transformation: [0.038f,-0.0325f,0f,0f,0.0325f,0.038f,0f,-0.9656f,0f,0f,0.05f,0.7875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner4) {transformation: [0.038f,-0.0325f,0f,0f,0.0325f,0.038f,0f,-0.9656f,0f,0f,0.05f,0.7875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner3) {transformation: [0.038f,-0.0325f,0f,0f,0.0325f,0.038f,0f,-0.9656f,0f,0f,0.05f,0.7875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}