# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_handle_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_string_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_body_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_bobber_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_reel_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_hook_item) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hook) {transformation: [0f,0f,0f,0f,0f,0f,0f,-0.375f,0f,0f,0f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner1) {transformation: [1f,0f,0f,0.1875f,0f,1f,0f,-0.2125f,0f,0f,1f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner2) {transformation: [1f,0f,0f,-0.1875f,0f,1f,0f,-0.2125f,0f,0f,1f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner4) {transformation: [1f,0f,0f,-0.1875f,0f,1f,0f,-0.45f,0f,0f,1f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_corner3) {transformation: [1f,0f,0f,0.1875f,0f,1f,0f,-0.45f,0f,0f,1f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}