# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.1923f,0f,0f,-1f,1.44f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.0673f,0f,0f,-1f,1.44f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5625f,0f,1.25f,0f,0.8077f,0f,0f,-1.25f,1.44f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5625f,0f,0.8616f,0.5075f,-0.8261f,0f,0.5075f,-0.8616f,0.5501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5625f,0f,1.1847f,0.6979f,-0.9615f,0f,0.6979f,-1.1847f,0.3797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5625f,0f,0.8616f,0.5075f,-1.5f,0f,0.5075f,-0.8616f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5625000000000001,"posy":0.8156283686866007,"posz":1.4265093504568926,"roty":0,"rotx":30.500000000000007}}}