# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.3774f,0f,0f,-1f,1.7109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2524f,0f,0f,-1f,1.7109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5625f,0f,1.25f,0f,0.6226f,0f,0f,-1.25f,1.7109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7934f,0.6088f,-0.8906f,0f,0.6088f,-0.7934f,0.6286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5625f,0f,1.0909f,0.837f,-1.0042f,0f,0.837f,-1.0909f,0.443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7934f,0.6088f,-1.5f,0f,0.6088f,-0.7934f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5625000000000001,"posy":0.6321371020326947,"posz":1.6985463404609367,"roty":0,"rotx":37.5}}}