# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,1.9832f,0f,0f,-1f,1.9169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,2.1082f,0f,0f,-1f,1.9169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.25f,0f,3.9832f,0f,0f,-1.25f,1.9169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.788f,0.6157f,2.4795f,0f,0.6157f,-0.788f,0.8214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.0835f,0.8465f,2.3675f,0f,0.8465f,-1.0835f,0.6348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.788f,0.6157f,1.875f,0f,0.6157f,-0.788f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":3.9927789003180654,"posz":1.904590214937707,"roty":0,"rotx":38.00000000000001}}}