# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,1.9388f,0f,0f,-1f,1.9715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,2.0638f,0f,0f,-1f,1.9715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.25f,0f,3.9388f,0f,0f,-1.25f,1.9715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.7716f,0.6361f,2.4643f,0f,0.6361f,-0.7716f,0.837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.061f,0.8746f,2.3573f,0f,0.8746f,-1.061f,0.6475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.7716f,0.6361f,1.875f,0f,0.6361f,-0.7716f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":3.9487410678544976,"posz":1.95946021699649,"roty":0,"rotx":39.5}}}