# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.4213f,0f,0f,-1f,1.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2963f,0f,0f,-1f,1.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5625f,0f,1.25f,0f,0.5787f,0f,0f,-1.25f,1.7659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7771f,0.6293f,-0.9056f,0f,0.6293f,-0.7771f,0.6444f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5625f,0f,1.0686f,0.8653f,-1.0143f,0f,0.8653f,-1.0686f,0.4558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7771f,0.6293f,-1.5f,0f,0.6293f,-0.7771f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5625000000000001,"posy":0.5885797714156091,"posz":1.7537985509464382,"roty":0,"rotx":39.00000000000001}}}