# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,1.9685f,0f,0f,-1f,1.9352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,2.0935f,0f,0f,-1f,1.9352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.25f,0f,3.9685f,0f,0f,-1.25f,1.9352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.7826f,0.6225f,2.4745f,0f,0.6225f,-0.7826f,0.8267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.0761f,0.856f,2.3641f,0f,0.856f,-1.0761f,0.6391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.7826f,0.6225f,1.875f,0f,0.6225f,-0.7826f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":3.978259421540862,"posz":1.9230080859636023,"roty":0,"rotx":38.5}}}