# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.4065f,0f,0f,-1f,1.7477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2815f,0f,0f,-1f,1.7477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5625f,0f,1.25f,0f,0.5935f,0f,0f,-1.25f,1.7477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7826f,0.6225f,-0.9005f,0f,0.6225f,-0.7826f,0.6392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5625f,0f,1.0761f,0.856f,-1.0109f,0f,0.856f,-1.0761f,0.4516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5625f,0f,0.7826f,0.6225f,-1.5f,0f,0.6225f,-0.7826f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5625000000000001,"posy":0.6032594215408624,"posz":1.7355080859636023,"roty":0,"rotx":38.5}}}