# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.2418f,0f,0f,-1f,1.5197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,-1.1168f,0f,0f,-1f,1.5197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5625f,0f,1.25f,0f,0.7582f,0f,0f,-1.25f,1.5197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5625f,0f,0.8434f,0.5373f,-0.8435f,0f,0.5373f,-0.8434f,0.5733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5625f,0f,1.1597f,0.7388f,-0.9729f,0f,0.7388f,-1.1597f,0.3983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5625f,0f,0.8434f,0.5373f,-1.5f,0f,0.5373f,-0.8434f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5625000000000001,"posy":0.7666145106221303,"posz":1.5064926974320891,"roty":0,"rotx":32.5}}}