# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,-1.5554f,0f,0f,-1f,1.6073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,-1.4304f,0f,0f,-1f,1.6073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.25f,0f,0.4446f,0f,0f,-1.25f,1.6073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.866f,0.5f,-1.1969f,0f,0.5f,-0.866f,0.7317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.1908f,0.6875f,-1.3337f,0f,0.6875f,-1.1908f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.866f,0.5f,-1.875f,0f,0.5f,-0.866f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":0.4524432726706791,"posz":1.5937499999999996,"roty":0,"rotx":30}}}