# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,0.7454f,0f,0f,-1f,1.7268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,0.8704f,0f,0f,-1f,1.7268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.25f,0f,2.7454f,0f,0f,-1.25f,1.7268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.8387f,0.5446f,1.152f,0f,0.5446f,-0.8387f,0.7666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.1532f,0.7489f,1.0242f,0f,0.7489f,-1.1532f,0.5904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.8387f,0.5446f,0.5f,0f,0.5446f,-0.8387f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":2.753927151353327,"posz":1.713717406602885,"roty":0,"rotx":33}}}