# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.uncommon] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_uncommon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.rare] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rare set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.epic] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_epic set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.legendary] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_legendary set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.model19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_model19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishname19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishname19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.fishcount19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_fishcount19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.common] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_common set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.text_display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.next] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_next set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.previous] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_previous set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.exit] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_exit set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.bestiary.node.biome] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_biome set from storage aj:uuid main.out