# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.main_ui.root] run return 0
execute on passengers if entity @s[tag=aj.main_ui.data] unless data entity @s {data:{rigHash: '13d1fff5571854df6a327810e4a25f1a19d9091ad6d4c2d859e0ccf33b4b60ef'}} on vehicle run function animated_java:main_ui/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1