# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.main_ui.root] run return 0
execute on passengers if entity @s[tag=aj.main_ui.data] unless data entity @s {data:{rigHash: '02138c8cf198d2f218115fb7bdd632ab485b7b0fa85bdeb9d386e12a5f882243'}} on vehicle run function animated_java:main_ui/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1