# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.main_ui.root] run return 0
execute on passengers if entity @s[tag=aj.main_ui.data] unless data entity @s {data:{rigHash: '7cf8e3a1f053ac8c61fa874d4ed0c99a7caa0b85e8dcdf91ab4ed9977f0e9485'}} on vehicle run function animated_java:main_ui/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1