# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,-0.0109f,0.9999f,0.7968f,0f,0.9999f,0.0109f,-2.5557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,-0.0109f,0.9999f,0.7955f,0f,0.9999f,0.0109f,-2.4307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,-0.0136f,1.2499f,0.775f,0f,1.2499f,0.0136f,-0.5558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.8434f,-0.5373f,-0.7596f,0f,-0.5373f,-0.8434f,0.4959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.1597f,-0.7388f,-0.9729f,0f,-0.7388f,-1.1597f,0.5392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.8434f,-0.5373f,-1.5f,0f,-0.5373f,-0.8434f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5,"posy":0.7666145106221303,"posz":-0.5689926974320894,"roty":0,"rotx":-32.5}}}