# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,0.4423f,0.8969f,-0.0493f,0f,0.8969f,-0.4423f,-2.249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,0.4423f,0.8969f,0.006f,0f,0.8969f,-0.4423f,-2.1369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,0.5529f,1.1211f,0.8353f,0f,1.1211f,-0.5529f,-0.4552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.866f,-0.5f,-0.7438f,0f,-0.5f,-0.866f,0.5286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.1908f,-0.6875f,-0.9587f,0f,-0.6875f,-1.1908f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.866f,-0.5f,-1.5f,0f,-0.5f,-0.866f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5,"posy":0.827443272670679,"posz":-0.4687499999999998,"roty":0,"rotx":-30}}}