# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,0.9848f,0.1736f,0.9727f,0f,0.1736f,-0.9848f,-0.5939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,0.9848f,0.1736f,1.0958f,0f,0.1736f,-0.9848f,-0.5722f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,1.231f,0.2171f,2.9423f,0f,0.2171f,-1.231f,-0.2466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.9063f,-0.4226f,1.2836f,0f,-0.4226f,-0.9063f,0.5958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.2462f,-0.5811f,1.0664f,0f,-0.5811f,-1.2462f,0.6109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.9063f,-0.4226f,0.5f,0f,-0.4226f,-0.9063f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5,"posy":2.9357021776609966,"posz":-0.2607865784281299,"roty":0,"rotx":-25}}}