# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,0.9848f,0.1736f,-1.0273f,0f,0.1736f,-0.9848f,-0.7814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,0.9848f,0.1736f,-0.9042f,0f,0.1736f,-0.9848f,-0.7597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,1.231f,0.2171f,0.9423f,0f,0.2171f,-1.231f,-0.4341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.9063f,-0.4226f,-0.7164f,0f,-0.4226f,-0.9063f,0.4083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.2462f,-0.5811f,-0.9336f,0f,-0.5811f,-1.2462f,0.4234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.9063f,-0.4226f,-1.5f,0f,-0.4226f,-0.9063f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5,"posy":0.9357021776609966,"posz":-0.4482865784281299,"roty":0,"rotx":-25}}}