# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.75f,0f,0.999f,0.0436f,-1.1785f,0f,0.0436f,-0.999f,1.3325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.75f,0f,0.999f,0.0436f,-1.0536f,0f,0.0436f,-0.999f,1.338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.75f,0f,1.2488f,0.0545f,0.8196f,0f,0.0545f,-1.2488f,1.4198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.75f,0f,0.866f,0.5f,-0.8219f,0f,0.5f,-0.866f,0.5442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.75f,0f,1.1908f,0.6875f,-0.9587f,0f,0.6875f,-1.1908f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.75f,0f,0.866f,0.5f,-1.5f,0f,0.5f,-0.866f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.7500000000000001,"posy":0.827443272670679,"posz":1.4062499999999996,"roty":0,"rotx":30}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fishing_rod/animations/retrieve/zzz/frames/35_root_commands