# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hook) {transformation: [-1f,0f,0f,-0.5f,0f,-0.9914f,-0.1305f,6.1931f,0f,-0.1305f,0.9914f,-0.1942f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bobber) {transformation: [-1f,0f,0f,-0.5f,0f,-0.9914f,-0.1305f,6.0692f,0f,-0.1305f,0.9914f,-0.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_string) {transformation: [-1.25f,0f,0f,-0.5f,0f,-1.2393f,-0.1632f,4.2103f,0f,-0.1632f,1.2393f,-0.4552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_reel) {transformation: [-1f,0f,0f,-0.5f,0f,0.866f,-0.5f,2.6312f,0f,-0.5f,-0.866f,0.5286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.375f,0f,0f,-0.5f,0f,1.1908f,-0.6875f,2.4163f,0f,-0.6875f,-1.1908f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_handle) {transformation: [-1f,0f,0f,-0.5f,0f,0.866f,-0.5f,1.875f,0f,-0.5f,-0.866f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.5,"posy":4.2024432726706795,"posz":-0.4687499999999998,"roty":0,"rotx":-30}}}