# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.fishing_rod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fishing_rod', 'function_path': 'animated_java:fishing_rod/animations/casting/next_frame'}
execute if score @s aj.casting.frame matches 46.. run scoreboard players set @s aj.casting.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.casting.frame
execute at @s run function animated_java:fishing_rod/animations/casting/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.casting.frame 1