# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.fishing_rod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fishing_rod', 'function_path': 'animated_java:fishing_rod/animations/casting/stop'}
tag @s remove aj.fishing_rod.animation.casting.playing
scoreboard players set @s aj.casting.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:fishing_rod/animations/casting/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only